### ISSUE TITLE
Update docs with a sample docker-compose.yml

### ISSUE THREAD

**Issue by kenayagi** [HSRNetwork/docker-powerdns-admin#2]
I've created the stack with something like:

    version: "2"
    
    services:
      pdnsapp:
        image: psitrax/powerdns:v4.2.0
        restart: always
        volumes:
          - ./pdns/app/conf.d:/etc/pdns/conf.d
        ports:
          - "53:53"
          - "53:53/udp"
        networks:
          net:
        environment:
          - MYSQL_HOST=pdnsdb
          - MYSQL_DB=pdns
          - MYSQL_USER=pdns
          - MYSQL_PASS=PdnsSqlUserPassword
        depends_on:
          - pdnsdb
    
      pdnsdb:
        image: mariadb:10.4.10
        restart: always
        volumes:
          - ./pdns/db/data:/var/lib/mysql
          - ./pdns/db/srv:/srv
          - ./pdns/db/conf.d:/etc/mysql/conf.d
        networks:
          net:
        environment:
          - MYSQL_ROOT_PASSWORD=PdnsSqlRootPassword
          - MYSQL_DATABASE=pdns
          - MYSQL_USER=pdns
          - MYSQL_PASSWORD=PdnsSqlUserPassword
          
      admdb:
        image: mariadb:10.4.10
        restart: always
        volumes:
          - ./admin/db/data:/var/lib/mysql
        networks:
          - net
        environment:
          - TZ=Europe/Rome
          - MYSQL_ROOT_PASSWORD=AdminSqlRootPassword
          - MYSQL_DATABASE=pdadm
          - MYSQL_USER=pdadm
          - MYSQL_PASSWORD=AdminSqlUserPassword
    
      admapp:
        image: hsrnetwork/powerdns-admin:1.0
        restart: always
        networks:
          net:
        ports:
          - "9191:9191"
        depends_on:
          - pdnsapp
          - admdb
        environment:
          - ADMIN_USER=admin
          - ADMIN_USER_PASSWORD=PowerAdminSuperSecretPassword
          - SECRET_KEY=RandomTokenRandomToken
          - LOG_LEVEL=INFO
          - SQLA_DB_HOST=admdb
          - SQLA_DB_NAME=pdadm
          - SQLA_DB_USER=pdadm
          - SQLA_DB_PASSWORD=AdminSqlUserPassword
          - PDNS_HOST=pdnsapp
          - PDNS_API_KEY=SecretApiSecretApi
          - PDNS_VERSION=4.2.0
    
          
    networks:
      net:

I think that it could be useful to add a similar sample to the docs.

**Comment by PhilipSchmid** [comment]
Uhm.. there is already an example `docker-compose.yml` file in this repository: https://github.com/HSRNetwork/docker-powerdns-admin/blob/master/docker-compose.yml

Regards,
Philip

**Comment by kenayagi** [comment]
I'm terribly sorry. Today I've evaluated a ton of dockerized powerdns-admin.. And I'm quite melted.
So I made a wrong comment (was _planned_ for another repo).

(This "issues" can't be deleted, or not?)
