### ISSUE TITLE
Cannot enable DNSSEC for this domain. 

### ISSUE THREAD

**Issue by firstdorsal** [HSRNetwork/docker-powerdns-admin#4]
I'm getting this error in the web interface:
Cannot enable DNSSEC for this domain. Error: Adding key failed, perhaps DNSSEC not enabled in configuration?

How can I enable DNSSEC?
is there a private key i need to store outside of docker?

how do i enable dns over https?

this project is the best/easiest regarding powerdns i found. 👍

**Comment by PhilipSchmid** [comment]
Hi @firstdorsal,

Thanks for your feedback. 

The PowerDNS Docker image which we use ([psitrax/powerdns](https://hub.docker.com/r/psitrax/powerdns/)) should support DNSSEC - you just need to enabled it via the environment variable `MYSQL_DNSSEC=yes` in the `environment` section of the `pdns-server` service (https://github.com/HSRNetwork/docker-powerdns-admin/blob/master/docker-compose.yml#L62).
See inside their [readme](https://github.com/psi-4ward/docker-powerdns/blob/master/README.md) for more information. 

Can you please test this? Unfortunately we do not use DNSSEC at the moment so I can't help you very much.

DoH has nothing to do with the PowerDNS admin UI. Please look it up inside the PowerDNS documentation.

Regards,
Philip

**Comment by firstdorsal** [comment]
hi @PhilipSchmid 
thank you for the quick reply!

pdns-server:
    image: psitrax/powerdns:4.1.10
    hostname: powerdns
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
    command: >
      --api=yes
      --api-key=SELF GENERATED KEY
      --webserver-address=0.0.0.0
      --webserver-allow-from=0.0.0.0/0
    environment:
      - MYSQL_HOST=pdns-server-mysql
      - MYSQL_DB=powerdns
      - MYSQL_USER=powerdns-svc-user
      - MYSQL_PASS=powerdns-svc-user-pw
      - MYSQL_DNSSEC=yes
    depends_on:
      - pdns-server-mysql


now looks like this but error is the same.

**Comment by PhilipSchmid** [comment]
Hi @firstdorsal 

Hmm.. can you plase exec into the running `psitrax/powerdns` container and check the `gmysql-dnssec` value inside `/etc/pdns/pdns.conf`? The entrypoint script from this image should set it properly (https://github.com/psi-4ward/docker-powerdns/blob/2cf9524f20d3ee691d796d7f4dd9401a2fe46ac4/entrypoint.sh#L54) but just to ensure it's really enabled there.

More information about this pdns configuration: https://doc.powerdns.com/authoritative/backends/generic-mysql.html#gmysql-dnssec

If it's enabled inside the `/etc/pdns/pdns.conf` configuration, I would need to check it on my local machine in the next days by myself.

Regards,
Philip

**Comment by firstdorsal** [comment]
/etc/pdns/pdns.conf shows:
gmysql-dnssec=yes

**i updated to: psitrax/powerdns:v4.3.0**
now its working
thank you!

**Comment by PhilipSchmid** [comment]
Thanks for the answer and solution. I updated the pdns image in the example `docker-compose.yaml` to version `v4.3.0`.

Regards,
Philip

**Comment by liudonghua123** [comment]
I use [pschiffe/pdns-mysql](https://hub.docker.com/r/pschiffe/pdns-mysql/) docker image which I need to config the similar `PDNS_gmysql_dnssec=yes` to enable DNSSEC, see also https://github.com/pschiffe/docker-pdns/issues/82.
