### ISSUE TITLE
DB access

### ISSUE THREAD

**Issue by fenice2** [HSRNetwork/docker-powerdns-admin#5]
Hi 

I'm just getting started with docker so my apologies for a beginners question.

I already have a running instance of PowerDNS-Admin and it uses an external Mysql 8 DB, do I just point this docker instance via the environment variables to my running DB server with all the correct information that I currently use?

**Comment by PhilipSchmid** [comment]
Hi @fenice2,

Yes, exactly. Just remove https://github.com/HSRNetwork/docker-powerdns-admin/blob/master/docker-compose.yml#L34-L48 and add the following lines to your `powerdns-admin` service:

```bash
    environment:
      ...
      SQLA_DB_HOST: your-external-db-host.example.com
      SQLA_DB_NAME: your-external-db-name
      SQLA_DB_USER: your-external-db-service-user
      SQLA_DB_PASSWORD: your-external-db-service-user-password
      ...
```

Regards,
Philip

**Comment by fenice2** [comment]
Hi

Thanks for the quick reply and confirmation. I've a rather steep l;earning curve ahead but an interesting one.

Thanks for producing this container, I'm looking forward to getting it running.

Regards

Bill
